# Generated by Django 5.2 on 2025-07-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True, verbose_name='Vehicle Number')),
                ('vehicle_type', models.CharField(choices=[('Bus', 'Bus'), ('Car', 'Car'), ('Truck', 'Truck'), ('Motorcycle', 'Motorcycle'), ('Van', 'Van')], max_length=20, verbose_name='Vehicle Type')),
                ('vehicle_owner', models.CharField(max_length=100, verbose_name='Vehicle Owner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['vehicle_number'],
            },
        ),
    ]
