# Generated by Django 5.2 on 2025-07-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routeMaster', '0002_alter_route_route_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='order',
        ),
        migrations.AddField(
            model_name='stop',
            name='fare_from_base',
            field=models.DecimalField(decimal_places=2, default='13', max_digits=6),
            preserve_default=False,
        ),
    ]
