# Generated by Django 5.2 on 2025-07-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrewMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_id', models.CharField(max_length=50, unique=True, verbose_name='Crew ID')),
                ('crew_name', models.CharField(max_length=100, verbose_name='Crew Name')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('role', models.CharField(choices=[('Conductor', 'Conductor'), ('Driver', 'Driver')], max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crew Master',
                'verbose_name_plural': 'Crew Masters',
                'db_table': 'crew_master',
                'ordering': ['crew_id'],
            },
        ),
    ]
