# Generated by Django 5.2 on 2025-07-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewmaster',
            name='email',
            field=models.EmailField(default='sdads@gmail.com', max_length=254, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crewmaster',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='QR Code'),
        ),
    ]
