# Generated by Django 5.2 on 2025-07-28 07:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crewMaster', '0002_crewmaster_email_crewmaster_qr_code'),
        ('routeMaster', '0001_initial'),
        ('scheduleMaster', '0001_initial'),
        ('vehicleMaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waybill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waybill_number', models.CharField(max_length=20, unique=True, verbose_name='Waybill Number')),
                ('waybill_date', models.DateField(default=datetime.date.today, verbose_name='Waybill Date')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20, verbose_name='Status')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(limit_choices_to={'role': 'Conductor', 'status': 'Active'}, on_delete=django.db.models.deletion.CASCADE, related_name='conductor_waybills', to='crewMaster.crewmaster', verbose_name='Conductor')),
                ('driver', models.ForeignKey(limit_choices_to={'role': 'Driver', 'status': 'Active'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_waybills', to='crewMaster.crewmaster', verbose_name='Driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routeMaster.route', verbose_name='Route')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduleMaster.schedulemaster', verbose_name='Schedule')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicleMaster.vehicle', verbose_name='Vehicle')),
            ],
            options={
                'verbose_name': 'Waybill',
                'verbose_name_plural': 'Waybills',
                'db_table': 'waybill_master',
                'ordering': ['-waybill_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaybillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Actual Amount')),
                ('etim_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ETIM Amount')),
                ('expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Expenses')),
                ('penalty_excess_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Penalty/Excess Amount')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Sales')),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Digital', 'Digital'), ('Mixed', 'Mixed')], default='Cash', max_length=20, verbose_name='Payment Method')),
                ('passenger_count', models.IntegerField(default=0, verbose_name='Passenger Count')),
                ('collection', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Collection')),
                ('payment_penalty_excess', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Payment Penalty/Excess Amount')),
                ('payment_total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Payment Total Sales')),
                ('total_cash_collection', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Cash Collection')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('fuel_consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Fuel Consumption (Liters)')),
                ('toll_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Toll Fees')),
                ('parking_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Parking Fees')),
                ('other_expenses', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Other Expenses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waybill', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='waybillMaster.waybill', verbose_name='Waybill')),
            ],
            options={
                'verbose_name': 'Waybill Detail',
                'verbose_name_plural': 'Waybill Details',
                'db_table': 'waybill_details',
            },
        ),
        migrations.CreateModel(
            name='WaybillTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.IntegerField(verbose_name='Trip Number')),
                ('route_name', models.CharField(max_length=100, verbose_name='Route Name')),
                ('direction', models.CharField(choices=[('North-South', 'North-South'), ('South-North', 'South-North')], max_length=20, verbose_name='Direction')),
                ('passenger_count', models.IntegerField(default=0, verbose_name='Passenger Count')),
                ('collection', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Collection')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Departure Time')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Arrival Time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('waybill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='waybillMaster.waybill', verbose_name='Waybill')),
            ],
            options={
                'verbose_name': 'Waybill Trip',
                'verbose_name_plural': 'Waybill Trips',
                'db_table': 'waybill_trips',
                'ordering': ['trip_number'],
                'unique_together': {('waybill', 'trip_number')},
            },
        ),
    ]
