# Generated by Django 5.2 on 2025-07-26 06:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=100, verbose_name='Schedule Name')),
                ('trips', models.PositiveIntegerField(help_text='Total number of trips for this schedule', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Number of Trips')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule Master',
                'verbose_name_plural': 'Schedule Masters',
                'db_table': 'schedule_master',
                'ordering': ['schedule_name', 'start_time'],
            },
        ),
    ]
