# Generated by Django 5.2 on 2025-07-26 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=50, unique=True, verbose_name='Admin ID')),
                ('admin_name', models.CharField(max_length=100, verbose_name='Admin Name')),
                ('role', models.CharField(choices=[('Bookkeeper', 'Bookkeeper'), ('Operations', 'Operations'), ('Manager', 'Manager')], max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Master',
                'verbose_name_plural': 'Admin Masters',
                'db_table': 'admin_master',
                'ordering': ['admin_id'],
            },
        ),
    ]
