# Generated by Django 5.2 on 2025-07-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmaster',
            options={},
        ),
        migrations.AddField(
            model_name='adminmaster',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='admin_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='admin_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='role',
            field=models.CharField(choices=[('Bookkeeper', 'Bookkeeper'), ('Operations', 'Operations'), ('Manager', 'Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminmaster',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
        migrations.AlterModelTable(
            name='adminmaster',
            table=None,
        ),
    ]
