# Generated by Django 5.2 on 2025-07-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminMaster', '0002_alter_adminmaster_options_adminmaster_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmaster',
            name='admin_email',
            field=models.EmailField(default='magat@gmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
